In [30]:
import pandas as pd

# Creating a DataFrame

data = {'Nome' : ['Marlon', 'Lucas', 'Ana'], "Idade" : [22, 25, 30], 'Salário' :  [1000, 2000, 3000]}
df = pd.DataFrame(data)

df

     Nome  Idade  Salário
0  Marlon     22     1000
1   Lucas     25     2000
2     Ana     30     3000

In [31]:
# Seleção por índice rotulado
print(df.loc[0])

Nome       Marlon
Idade          22
Salário      1000
Name: 0, dtype: object

In [32]:
# Seleção da linha que está na posição 1

print(df.iloc[0])

Nome       Marlon
Idade          22
Salário      1000
Name: 0, dtype: object

In [33]:
# Filtrando por um critério

filtro = df[df['Idade'] > 23]
filtro

    Nome  Idade  Salário
1  Lucas     25     2000
2    Ana     30     3000

In [34]:
# Changing some element of a column

df.loc[0, "Salário"] = 1250
df

     Nome  Idade  Salário
0  Marlon     22     1250
1   Lucas     25     2000
2     Ana     30     3000

In [35]:
df["Estado"] = ['SP', 'RJ', 'MG']
df

     Nome  Idade  Salário Estado
0  Marlon     22     1250     SP
1   Lucas     25     2000     RJ
2     Ana     30     3000     MG

In [36]:
# TO remove a column

df = df.drop('Estado', axis=1)
df

     Nome  Idade  Salário
0  Marlon     22     1250
1   Lucas     25     2000
2     Ana     30     3000

In [37]:
# Ordeanando por Idade
df_ordenado = df.sort_values(by="Idade")
df_ordenado

     Nome  Idade  Salário
0  Marlon     22     1250
1   Lucas     25     2000
2     Ana     30     3000

In [38]:
# Ordenando descrecentemente

df_ordenado = df.sort_values(by='Idade', ascending = False)
df_ordenado

     Nome  Idade  Salário
2     Ana     30     3000
1   Lucas     25     2000
0  Marlon     22     1250

In [39]:
# Para fazer uma operação em toda a coluna

df["Salário"] = df['Salário'].apply(lambda x: x * 2)
df

     Nome  Idade  Salário
0  Marlon     22     2500
1   Lucas     25     4000
2     Ana     30     6000

In [44]:
# Checando se há valor nulu

df_nulos = pd.DataFrame({'Nome': ['Alice', 'Julia', None], "Idade" : [25, None, 30]})

print(df_nulos.isna())

    Nome  Idade
0  False  False
1  False   True
2   True  False

In [45]:
# Preenchendo os nulos

df_nulos.Idade = df_nulos['Idade'].fillna(df_nulos.Idade.mean())
df_nulos

    Nome  Idade
0  Alice   25.0
1  Julia   27.5
2   None   30.0

In [46]:
# Removendo os nulos

df_nulos= df_nulos.dropna()
df_nulos

    Nome  Idade
0  Alice   25.0
1  Julia   27.5